# Generated by Django 5.2.17 on 2026-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.CharField(max_length=40, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=20)),
                ('lang', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('accuracy', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('at', models.DateTimeField(db_index=True)),
                ('doc', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('doc', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=80, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField()),
                ('doc', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='User ID')),
                ('username', models.CharField(max_length=40)),
                ('username_key', models.CharField(editable=False, max_length=40, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('xp', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'player',
                'ordering': ['user_id'],
            },
        ),
    ]
